package calculator;


/**
* calculator/simplecalOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Thursday, 19 June 2014 04:58:44 o'clock IST
*/

public interface simplecalOperations 
{
  double addfn (double a, double b);
  double subfn (double a, double b);
  double mulfn (double a, double b);
  double divfn (double a, double b);
  double modfn (double a, double b);
  double sqrtfn (double a);
  double powerfn (double a, double b);
} // interface simplecalOperations
