package calculator;


/**
* calculator/simplecal.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Thursday, 19 June 2014 04:58:44 o'clock IST
*/

public interface simplecal extends simplecalOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface simplecal
