package calculator;

/**
* calculator/simplecalHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Thursday, 19 June 2014 04:58:44 o'clock IST
*/

public final class simplecalHolder implements org.omg.CORBA.portable.Streamable
{
  public calculator.simplecal value = null;

  public simplecalHolder ()
  {
  }

  public simplecalHolder (calculator.simplecal initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = calculator.simplecalHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    calculator.simplecalHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return calculator.simplecalHelper.type ();
  }

}
