package calculator;


/**
* calculator/simplecalHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Thursday, 19 June 2014 04:58:44 o'clock IST
*/

abstract public class simplecalHelper
{
  private static String  _id = "IDL:calculator/simplecal:1.0";

  public static void insert (org.omg.CORBA.Any a, calculator.simplecal that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static calculator.simplecal extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (calculator.simplecalHelper.id (), "simplecal");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static calculator.simplecal read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_simplecalStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, calculator.simplecal value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static calculator.simplecal narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof calculator.simplecal)
      return (calculator.simplecal)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      calculator._simplecalStub stub = new calculator._simplecalStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static calculator.simplecal unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof calculator.simplecal)
      return (calculator.simplecal)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      calculator._simplecalStub stub = new calculator._simplecalStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
