package calculator;


/**
* calculator/simplecalPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Thursday, 19 June 2014 04:58:44 o'clock IST
*/

public abstract class simplecalPOA extends org.omg.PortableServer.Servant
 implements calculator.simplecalOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addfn", new java.lang.Integer (0));
    _methods.put ("subfn", new java.lang.Integer (1));
    _methods.put ("mulfn", new java.lang.Integer (2));
    _methods.put ("divfn", new java.lang.Integer (3));
    _methods.put ("modfn", new java.lang.Integer (4));
    _methods.put ("sqrtfn", new java.lang.Integer (5));
    _methods.put ("powerfn", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // calculator/simplecal/addfn
       {
         double a = in.read_double ();
         double b = in.read_double ();
         double $result = (double)0;
         $result = this.addfn (a, b);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 1:  // calculator/simplecal/subfn
       {
         double a = in.read_double ();
         double b = in.read_double ();
         double $result = (double)0;
         $result = this.subfn (a, b);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 2:  // calculator/simplecal/mulfn
       {
         double a = in.read_double ();
         double b = in.read_double ();
         double $result = (double)0;
         $result = this.mulfn (a, b);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 3:  // calculator/simplecal/divfn
       {
         double a = in.read_double ();
         double b = in.read_double ();
         double $result = (double)0;
         $result = this.divfn (a, b);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 4:  // calculator/simplecal/modfn
       {
         double a = in.read_double ();
         double b = in.read_double ();
         double $result = (double)0;
         $result = this.modfn (a, b);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 5:  // calculator/simplecal/sqrtfn
       {
         double a = in.read_double ();
         double $result = (double)0;
         $result = this.sqrtfn (a);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 6:  // calculator/simplecal/powerfn
       {
         double a = in.read_double ();
         double b = in.read_double ();
         double $result = (double)0;
         $result = this.powerfn (a, b);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:calculator/simplecal:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public simplecal _this() 
  {
    return simplecalHelper.narrow(
    super._this_object());
  }

  public simplecal _this(org.omg.CORBA.ORB orb) 
  {
    return simplecalHelper.narrow(
    super._this_object(orb));
  }


} // class simplecalPOA
